"""Deterministic entity/identity verification policy for PUL7SAR Phase 18.

This module verifies identity evidence; it does not discover identities.  The policy
is intentionally fail-closed: every story-visible entity reference must resolve to
exactly one source-backed canonical entity and every exact entity asset must be an
explicit approved, non-generated byte-bound asset.  Passing this gate grants no
factual, sentiment, generation, visual-quality, brand, human-review, Golden, or
publication authority.
"""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re
import unicodedata
from typing import Any, Mapping, Sequence

from engine.entities.normalizer import normalize_entity_key


IDENTITY_EVIDENCE_SCHEMA = "pul7sar-phase18-entity-identity-evidence-v1"
IDENTITY_GATE_ID = "entity_identity_verification"
VERIFIER_ID = "pul7sar.production.entity_identity_verification"
VERIFIER_VERSION = "1.0.0"

_REQUIRED_EVIDENCE_FIELDS = (
    "schema",
    "gate_id",
    "story_snapshot_sha256",
    "canonical_entities",
    "story_entity_references",
    "exact_entity_assets",
)
_ENTITY_FIELDS = (
    "entity_id",
    "kind",
    "display_name",
    "aliases",
    "identity_source_refs",
)
_REFERENCE_FIELDS = ("field", "text", "expected_entity_id")
_ASSET_FIELDS = (
    "entity_id",
    "asset_kind",
    "asset_sha256",
    "origin",
    "generated",
    "approved_for_exact_use",
)
_STABLE_ID = re.compile(r"^[a-z0-9][a-z0-9_.:-]*$")
_WS = re.compile(r"\s+")


@dataclass(frozen=True)
class IdentityDecision:
    allowed: bool
    canonical_entity_count: int
    resolved_reference_count: int
    exact_asset_count: int
    alias_collision_count: int
    unresolved_reference_count: int


def _clean_text(value: str) -> str:
    return _WS.sub(" ", unicodedata.normalize("NFKC", value).strip()).strip()


def _identity_token(value: str) -> str:
    cleaned = _clean_text(value).casefold()
    cleaned = re.sub(r"[\s_-]+", " ", cleaned)
    return cleaned.strip()


def _is_sha256(value: Any) -> bool:
    return (
        isinstance(value, str)
        and len(value) == 64
        and all(ch in "0123456789abcdef" for ch in value.lower())
    )


def _require_nonempty_text(value: Any, code: str) -> str:
    if not isinstance(value, str) or not _clean_text(value):
        raise ValueError(code)
    return _clean_text(value)


def _load_evidence(evidence_path: Path) -> tuple[dict[str, Any], bytes]:
    if not isinstance(evidence_path, Path) or not evidence_path.is_file():
        raise ValueError("QWEN_IDENTITY_EVIDENCE_MISSING")
    raw = evidence_path.read_bytes()
    if not raw:
        raise ValueError("QWEN_IDENTITY_EVIDENCE_EMPTY")
    try:
        payload = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError("QWEN_IDENTITY_EVIDENCE_JSON_INVALID") from exc
    if not isinstance(payload, dict) or tuple(payload.keys()) != _REQUIRED_EVIDENCE_FIELDS:
        raise ValueError("QWEN_IDENTITY_EVIDENCE_SHAPE_INVALID")
    return payload, raw


def _canonical_alias_tokens(entity: Mapping[str, Any]) -> tuple[str, ...]:
    if tuple(entity.keys()) != _ENTITY_FIELDS:
        raise ValueError("PUL7SAR_IDENTITY_ENTITY_SHAPE_INVALID")

    entity_id = _require_nonempty_text(entity["entity_id"], "PUL7SAR_IDENTITY_ENTITY_ID_REQUIRED")
    if not _STABLE_ID.fullmatch(entity_id):
        raise ValueError("PUL7SAR_IDENTITY_ENTITY_ID_INVALID")
    _require_nonempty_text(entity["kind"], "PUL7SAR_IDENTITY_ENTITY_KIND_REQUIRED")
    display_name = _require_nonempty_text(
        entity["display_name"], "PUL7SAR_IDENTITY_DISPLAY_NAME_REQUIRED"
    )

    aliases = entity["aliases"]
    if not isinstance(aliases, list):
        raise ValueError("PUL7SAR_IDENTITY_ALIASES_INVALID")
    source_refs = entity["identity_source_refs"]
    if not isinstance(source_refs, list) or not source_refs:
        raise ValueError("PUL7SAR_IDENTITY_SOURCE_REFS_REQUIRED")
    normalized_sources: set[str] = set()
    for source in source_refs:
        source_text = _require_nonempty_text(source, "PUL7SAR_IDENTITY_SOURCE_REF_INVALID")
        source_token = source_text.casefold()
        if source_token in normalized_sources:
            raise ValueError("PUL7SAR_IDENTITY_SOURCE_REF_DUPLICATE")
        normalized_sources.add(source_token)

    values = [entity_id, display_name]
    values.extend(aliases)
    tokens: list[str] = []
    for value in values:
        text = _require_nonempty_text(value, "PUL7SAR_IDENTITY_ALIAS_INVALID")
        token = _identity_token(text)
        if token not in tokens:
            tokens.append(token)
        normalized_key = normalize_entity_key(text)
        if normalized_key:
            normalized_token = _identity_token(normalized_key)
            if normalized_token not in tokens:
                tokens.append(normalized_token)
    return tuple(tokens)


def evaluate_entity_identity(
    *,
    canonical_entities: Sequence[Mapping[str, Any]],
    story_entity_references: Sequence[Mapping[str, Any]],
    exact_entity_assets: Sequence[Mapping[str, Any]],
) -> IdentityDecision:
    """Verify deterministic source-backed entity resolution and exact-asset binding."""
    if not isinstance(canonical_entities, list) or not canonical_entities:
        raise ValueError("PUL7SAR_IDENTITY_CANONICAL_ENTITIES_REQUIRED")
    if not isinstance(story_entity_references, list) or not story_entity_references:
        raise ValueError("PUL7SAR_IDENTITY_STORY_REFERENCES_REQUIRED")
    if not isinstance(exact_entity_assets, list):
        raise ValueError("PUL7SAR_IDENTITY_EXACT_ASSETS_INVALID")

    entities_by_id: dict[str, Mapping[str, Any]] = {}
    alias_owner: dict[str, str] = {}
    collisions: set[str] = set()

    for entity in canonical_entities:
        if not isinstance(entity, Mapping):
            raise ValueError("PUL7SAR_IDENTITY_ENTITY_INVALID")
        entity_id = _require_nonempty_text(
            entity.get("entity_id"), "PUL7SAR_IDENTITY_ENTITY_ID_REQUIRED"
        )
        if entity_id in entities_by_id:
            raise ValueError("PUL7SAR_IDENTITY_ENTITY_ID_DUPLICATE")
        tokens = _canonical_alias_tokens(entity)
        entities_by_id[entity_id] = entity
        for token in tokens:
            owner = alias_owner.get(token)
            if owner is not None and owner != entity_id:
                collisions.add(token)
            else:
                alias_owner[token] = entity_id

    if collisions:
        raise ValueError("PUL7SAR_IDENTITY_ALIAS_COLLISION")

    resolved = 0
    unresolved = 0
    seen_refs: set[tuple[str, str, str]] = set()
    for reference in story_entity_references:
        if not isinstance(reference, Mapping) or tuple(reference.keys()) != _REFERENCE_FIELDS:
            raise ValueError("PUL7SAR_IDENTITY_REFERENCE_SHAPE_INVALID")
        field = _require_nonempty_text(reference["field"], "PUL7SAR_IDENTITY_REFERENCE_FIELD_INVALID")
        text = _require_nonempty_text(reference["text"], "PUL7SAR_IDENTITY_REFERENCE_TEXT_INVALID")
        expected = _require_nonempty_text(
            reference["expected_entity_id"], "PUL7SAR_IDENTITY_REFERENCE_EXPECTED_ID_INVALID"
        )
        if expected not in entities_by_id:
            raise ValueError("PUL7SAR_IDENTITY_REFERENCE_UNKNOWN_EXPECTED_ID")
        ref_key = (field.casefold(), _identity_token(text), expected)
        if ref_key in seen_refs:
            raise ValueError("PUL7SAR_IDENTITY_REFERENCE_DUPLICATE")
        seen_refs.add(ref_key)

        candidate_tokens = {_identity_token(text)}
        normalized_key = normalize_entity_key(text)
        if normalized_key:
            candidate_tokens.add(_identity_token(normalized_key))
        owners = {alias_owner[token] for token in candidate_tokens if token in alias_owner}
        if owners != {expected}:
            unresolved += 1
            continue
        resolved += 1

    if unresolved:
        raise ValueError("PUL7SAR_IDENTITY_REFERENCE_UNRESOLVED_OR_MISMATCHED")

    seen_assets: set[tuple[str, str]] = set()
    for asset in exact_entity_assets:
        if not isinstance(asset, Mapping) or tuple(asset.keys()) != _ASSET_FIELDS:
            raise ValueError("PUL7SAR_IDENTITY_ASSET_SHAPE_INVALID")
        entity_id = _require_nonempty_text(asset["entity_id"], "PUL7SAR_IDENTITY_ASSET_ENTITY_INVALID")
        if entity_id not in entities_by_id:
            raise ValueError("PUL7SAR_IDENTITY_ASSET_UNKNOWN_ENTITY")
        asset_kind = _require_nonempty_text(asset["asset_kind"], "PUL7SAR_IDENTITY_ASSET_KIND_INVALID")
        if not _is_sha256(asset["asset_sha256"]):
            raise ValueError("PUL7SAR_IDENTITY_ASSET_SHA_INVALID")
        if asset["origin"] != "approved_exact_asset":
            raise ValueError("PUL7SAR_IDENTITY_ASSET_ORIGIN_NOT_APPROVED")
        if asset["generated"] is not False:
            raise ValueError("PUL7SAR_IDENTITY_GENERATED_EXACT_ASSET_FORBIDDEN")
        if asset["approved_for_exact_use"] is not True:
            raise ValueError("PUL7SAR_IDENTITY_ASSET_EXACT_USE_NOT_APPROVED")
        asset_key = (entity_id, asset_kind.casefold())
        if asset_key in seen_assets:
            raise ValueError("PUL7SAR_IDENTITY_ASSET_DUPLICATE")
        seen_assets.add(asset_key)

    return IdentityDecision(
        allowed=True,
        canonical_entity_count=len(entities_by_id),
        resolved_reference_count=resolved,
        exact_asset_count=len(exact_entity_assets),
        alias_collision_count=0,
        unresolved_reference_count=0,
    )


def verify_entity_identity_evidence(
    evidence_path: Path,
    story_snapshot_sha256: str,
    receipt: Mapping[str, Any],
) -> Mapping[str, Any]:
    """Replay-compatible production verifier over exact identity evidence bytes."""
    if not _is_sha256(story_snapshot_sha256):
        raise ValueError("QWEN_IDENTITY_STORY_SHA_INVALID")
    if not isinstance(receipt, Mapping):
        raise ValueError("QWEN_IDENTITY_RECEIPT_INVALID")
    if receipt.get("verifier_id") != VERIFIER_ID:
        raise ValueError("QWEN_IDENTITY_VERIFIER_ID_MISMATCH")
    if receipt.get("verifier_version") != VERIFIER_VERSION:
        raise ValueError("QWEN_IDENTITY_VERIFIER_VERSION_MISMATCH")

    evidence, raw = _load_evidence(evidence_path)
    if evidence["schema"] != IDENTITY_EVIDENCE_SCHEMA:
        raise ValueError("QWEN_IDENTITY_EVIDENCE_SCHEMA_DRIFT")
    if evidence["gate_id"] != IDENTITY_GATE_ID:
        raise ValueError("QWEN_IDENTITY_GATE_DRIFT")
    if evidence["story_snapshot_sha256"] != story_snapshot_sha256:
        raise ValueError("QWEN_IDENTITY_CROSS_STORY_EVIDENCE")

    decision = evaluate_entity_identity(
        canonical_entities=evidence["canonical_entities"],
        story_entity_references=evidence["story_entity_references"],
        exact_entity_assets=evidence["exact_entity_assets"],
    )
    if decision.allowed is not True:
        raise ValueError("QWEN_IDENTITY_SEMANTIC_REJECTED")

    details = {
        "canonical_entity_count": decision.canonical_entity_count,
        "resolved_reference_count": decision.resolved_reference_count,
        "exact_asset_count": decision.exact_asset_count,
        "alias_collision_count": decision.alias_collision_count,
        "unresolved_reference_count": decision.unresolved_reference_count,
        "all_story_entities_uniquely_resolved": True,
        "all_canonical_entities_source_backed": True,
        "generated_exact_entity_assets_forbidden": True,
    }
    return {
        "gate_id": IDENTITY_GATE_ID,
        "story_snapshot_sha256": story_snapshot_sha256,
        "source_evidence_sha256": hashlib.sha256(raw).hexdigest(),
        "source_evidence_byte_size": len(raw),
        "verifier_id": VERIFIER_ID,
        "verifier_version": VERIFIER_VERSION,
        "gate_passed": True,
        "verification_details": details,
    }
